import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import React from 'react';
import Navbar from '@/components/nav/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang='en' className='h-full'>
			<body className={cn('relative antialiased font-sans', inter.className)}>
				<main className='relative flex min-h-screen flex-col'>
					<Navbar />
					{children}
				</main>
			</body>
		</html>
	);
}
